import { AppointmentItem } from './types';

export const APPOINTMENT_DATA: AppointmentItem[] = [
  // ─── MORNING (8 AM – 12 PM) ──────────────────────────────────────────────
  {
    id: 'apt-001', refNumber: 'APT-5001', type: 'service',
    customerName: 'Marcus Rivera', customerInitials: 'MR',
    vehicle: '2022 Honda Accord Sport',
    scheduledTime: '8:00 AM', timeGroup: 'morning',
    assignedTo: 'Jordan Davis', assignedRole: 'advisor',
    status: 'checked-in', source: 'portal',
    services: ['Oil Change', 'Tire Rotation', 'Multi-Point Inspection'],
    estimatedValue: '$185', estimatedDuration: '1.5h',
  },
  {
    id: 'apt-002', refNumber: 'APT-5002', type: 'sales-consultation',
    customerName: 'Olivia Pham', customerInitials: 'OP',
    vehicle: '2023 Toyota Camry XSE',
    scheduledTime: '9:00 AM', timeGroup: 'morning',
    assignedTo: 'Alex Torres', assignedRole: 'sales',
    status: 'in-consultation', source: 'crm',
    estimatedValue: '$31,200',
    notes: 'Returning customer — financing discussion, 72mo @ 6.9% APR',
  },
  {
    id: 'apt-003', refNumber: 'APT-5003', type: 'service',
    customerName: 'Patricia Moore', customerInitials: 'PM',
    vehicle: '2023 Chevrolet Silverado',
    scheduledTime: '9:30 AM', timeGroup: 'morning',
    assignedTo: 'Jordan Davis', assignedRole: 'advisor',
    status: 'ro-created', source: 'phone',
    services: ['Engine Diagnostic', 'Brake Inspection'],
    estimatedValue: '$1,890', estimatedDuration: '3h',
    hasFlag: true, unreadMessages: 2,
    roNumber: 'RO-10290',
    notes: 'Waiting on customer approval — authorization $1,890',
  },
  {
    id: 'apt-004', refNumber: 'APT-5004', type: 'test-drive',
    customerName: 'Brandon Hicks', customerInitials: 'BH',
    vehicle: '2024 Ford Mustang Mach-E',
    scheduledTime: '10:00 AM', timeGroup: 'morning',
    assignedTo: 'Michelle Grant', assignedRole: 'sales',
    status: 'in-consultation', source: 'autotrader',
    estimatedValue: '$52,400', estimatedDuration: '45m',
    hasFlag: true,
    notes: 'Pre-approved financing · Trade-in: 2019 Honda Civic',
  },
  {
    id: 'apt-005', refNumber: 'APT-5005', type: 'service',
    customerName: 'Robert Kim', customerInitials: 'RK',
    vehicle: '2021 Nissan Rogue',
    scheduledTime: '10:30 AM', timeGroup: 'morning',
    assignedTo: 'Jordan Davis', assignedRole: 'advisor',
    status: 'confirmed', source: 'portal',
    services: ['CVT Service', 'Cabin Air Filter Replacement'],
    estimatedValue: '$420', estimatedDuration: '2h',
  },
  {
    id: 'apt-006', refNumber: 'APT-5006', type: 'walk-in',
    customerName: 'Sarah Chen', customerInitials: 'SC',
    vehicle: '2019 Toyota Camry LE',
    scheduledTime: '11:00 AM', timeGroup: 'morning',
    assignedTo: 'Chris Patel', assignedRole: 'advisor',
    status: 'walkaround', source: 'walk-in',
    services: ['Alternator Replacement'],
    estimatedValue: '$850', estimatedDuration: '2.5h',
    notes: 'Walk-in — vehicle stalled nearby, towed in',
  },
  {
    id: 'apt-007', refNumber: 'APT-5007', type: 'service',
    customerName: 'Angela Foster', customerInitials: 'AF',
    vehicle: '2020 Hyundai Tucson',
    scheduledTime: '11:30 AM', timeGroup: 'morning',
    assignedTo: 'Jordan Davis', assignedRole: 'advisor',
    status: 'confirmed', source: 'phone',
    services: ['Tire Rotation', 'Wheel Alignment Check'],
    estimatedValue: '$180', estimatedDuration: '1h',
  },

  // ─── AFTERNOON (12 PM – 5 PM) ─────────────────────────────────────────────
  {
    id: 'apt-008', refNumber: 'APT-5008', type: 'sales-consultation',
    customerName: 'James Carter', customerInitials: 'JC',
    vehicle: '2024 Chevrolet Equinox EV',
    scheduledTime: '1:00 PM', timeGroup: 'afternoon',
    assignedTo: 'Alex Torres', assignedRole: 'sales',
    status: 'confirmed', source: 'autotrader',
    estimatedValue: '$38,900',
    notes: 'First visit — EV transition consultation + test drive',
  },
  {
    id: 'apt-009', refNumber: 'APT-5009', type: 'service',
    customerName: 'Daniel Cruz', customerInitials: 'DC',
    vehicle: '2019 Kia Sorento',
    scheduledTime: '1:30 PM', timeGroup: 'afternoon',
    assignedTo: 'Chris Patel', assignedRole: 'advisor',
    status: 'pending', source: 'portal',
    services: ['Brake Pad Replacement', 'Rotor Resurfacing'],
    estimatedValue: '$890', estimatedDuration: '2.5h',
    hasFlag: true,
    notes: 'Parts delay — customer notified, pending new time confirmation',
  },
  {
    id: 'apt-010', refNumber: 'APT-5010', type: 'service',
    customerName: 'Lisa Zhang', customerInitials: 'LZ',
    vehicle: '2022 Mazda CX-5',
    scheduledTime: '2:00 PM', timeGroup: 'afternoon',
    assignedTo: 'Jordan Davis', assignedRole: 'advisor',
    status: 'confirmed', source: 'portal',
    services: ['Oil Change', 'Multi-Point Inspection'],
    estimatedValue: '$95', estimatedDuration: '1h',
  },
  {
    id: 'apt-011', refNumber: 'APT-5011', type: 'sales-consultation',
    customerName: 'Mia Rodriguez', customerInitials: 'MR',
    vehicle: '2024 BMW X3 xDrive30i',
    scheduledTime: '2:30 PM', timeGroup: 'afternoon',
    assignedTo: 'Michelle Grant', assignedRole: 'sales',
    status: 'pending', source: 'portal',
    estimatedValue: '$58,700',
    unreadMessages: 1,
    notes: 'Lease inquiry — needs full pricing breakdown and F&I options',
  },
  {
    id: 'apt-012', refNumber: 'APT-5012', type: 'test-drive',
    customerName: 'Nathan Brooks', customerInitials: 'NB',
    vehicle: '2023 Honda CR-V Hybrid',
    scheduledTime: '3:30 PM', timeGroup: 'afternoon',
    assignedTo: 'Alex Torres', assignedRole: 'sales',
    status: 'confirmed', source: 'crm',
    estimatedValue: '$34,500', estimatedDuration: '30m',
    notes: 'Returning customer — lease ending April, considering Hybrid',
  },
  {
    id: 'apt-013', refNumber: 'APT-5013', type: 'service',
    customerName: 'David Thompson', customerInitials: 'DT',
    vehicle: '2020 Ford F-150 XLT',
    scheduledTime: '4:00 PM', timeGroup: 'afternoon',
    assignedTo: 'Chris Patel', assignedRole: 'advisor',
    status: 'confirmed', source: 'phone',
    services: ['Transmission Service', 'Fluid Flush'],
    estimatedValue: '$650', estimatedDuration: '2h',
  },

  // ─── EVENING (5 PM+) ──────────────────────────────────────────────────────
  {
    id: 'apt-014', refNumber: 'APT-5014', type: 'sales-consultation',
    customerName: 'Kevin Park', customerInitials: 'KP',
    vehicle: '2024 Tesla Model Y Long Range',
    scheduledTime: '5:00 PM', timeGroup: 'evening',
    assignedTo: 'Michelle Grant', assignedRole: 'sales',
    status: 'confirmed', source: 'portal',
    estimatedValue: '$48,990',
    notes: 'EV first-timer — needs full walkthrough and charging setup demo',
  },
  {
    id: 'apt-015', refNumber: 'APT-5015', type: 'follow-up',
    customerName: 'Sophie Anderson', customerInitials: 'SA',
    vehicle: '2022 Jeep Grand Cherokee',
    scheduledTime: '5:30 PM', timeGroup: 'evening',
    assignedTo: 'Alex Torres', assignedRole: 'sales',
    status: 'completed',
    source: 'showroom',
    estimatedValue: '$47,200',
    notes: 'Deal closed this morning — follow-up call for paperwork review',
  },
  {
    id: 'apt-016', refNumber: 'APT-5016', type: 'service',
    customerName: 'Elena Vasquez', customerInitials: 'EV',
    vehicle: '2020 Audi Q5 Premium',
    scheduledTime: '6:00 PM', timeGroup: 'evening',
    assignedTo: 'Jordan Davis', assignedRole: 'advisor',
    status: 'confirmed', source: 'portal',
    services: ['Suspension Inspection', 'Wheel Alignment'],
    estimatedValue: '$480', estimatedDuration: '1.5h',
  },
];