import { RoleConfig } from './types';

export const ROLE_CONFIGS: Record<string, RoleConfig> = {
  technician: {
    id: 'technician',
    label: 'Technician',
    avatarColor: 'bg-blue-600',
    primarySectionTitle: 'My Assigned Jobs',
    secondarySectionTitle: "Today's Summary",
    summary: [
      { label: 'Active', count: 2, color: 'blue' },
      { label: 'Waiting Parts', count: 1, color: 'amber' },
      { label: 'Completed', count: 3, color: 'green' },
      { label: 'Blocked', count: 0, color: 'red' },
    ],
    nba: {
      label: 'Clock In to Bay 4',
      description: 'RO #10284 is ready to start — customer waiting',
      urgency: 'high',
    },
    queue: [
      {
        id: 'j1', refNumber: 'RO-10284', customerName: 'Marcus Rivera', customerInitials: 'MR',
        vehicle: '2022 Honda Accord Sport', status: 'in-progress', priority: 'high',
        timeLabel: '2h 15m elapsed', subLabel: 'Oil Change + Brake Inspection',
        bay: 'Bay 4', totalHours: 3, hoursElapsed: 2.25, tags: ['Warranty'],
      },
      {
        id: 'j2', refNumber: 'RO-10291', customerName: 'Sarah Chen', customerInitials: 'SC',
        vehicle: '2019 Toyota Camry LE', status: 'waiting-parts', priority: 'medium',
        timeLabel: 'Parts ETA: 1:30 PM', subLabel: 'Alternator Replacement',
        bay: 'Bay 2', totalHours: 4, hoursElapsed: 1.5, tags: ['Parts Ordered'],
      },
      {
        id: 'j3', refNumber: 'RO-10277', customerName: 'David Thompson', customerInitials: 'DT',
        vehicle: '2020 Ford F-150 XLT', status: 'not-started', priority: 'medium',
        timeLabel: 'Scheduled 2:00 PM', subLabel: 'Transmission Service',
        bay: 'Bay 6', totalHours: 2.5, hoursElapsed: 0,
      },
      {
        id: 'j4', refNumber: 'RO-10265', customerName: 'Jennifer Walsh', customerInitials: 'JW',
        vehicle: '2021 Subaru Outback', status: 'completed', priority: 'low',
        timeLabel: 'Done at 11:22 AM', subLabel: 'Multi-Point Inspection',
        bay: 'Bay 1', totalHours: 1, hoursElapsed: 1,
      },
      {
        id: 'j5', refNumber: 'RO-10259', customerName: 'Kevin Park', customerInitials: 'KP',
        vehicle: '2018 BMW 3 Series', status: 'completed', priority: 'high',
        timeLabel: 'Done at 10:05 AM', subLabel: 'Timing Chain + Water Pump',
        bay: 'Bay 3', totalHours: 6, hoursElapsed: 6, tags: ['Premium'],
      },
    ],
    navItems: [
      { id: 'dashboard',  label: 'Dashboard',      icon: 'LayoutDashboard', path: '/',            section: 'Main' },
      { id: 'my-jobs',    label: 'My Jobs',        icon: 'Wrench',          path: '/jobs',        badge: 3, section: 'Main' },
      { id: 'inspection', label: 'Inspection',     icon: 'ClipboardList',   path: '/inspection',  badge: 1, section: 'Main' },
      { id: 'clock',      label: 'Time & Labor',   icon: 'Clock',           path: '/time',        section: 'Main' },
      { id: 'parts',      label: 'Parts Requests', icon: 'Package',         path: '/parts',       badge: 1, section: 'Main' },
      { id: 'vehicles',   label: 'Vehicles',       icon: 'Car',             path: '/vehicles',    section: 'Records' },
      { id: 'settings',   label: 'Settings',       icon: 'Settings',        path: '/settings',    section: 'Account' },
    ],
  },

  advisor: {
    id: 'advisor',
    label: 'Service Advisor',
    avatarColor: 'bg-emerald-600',
    primarySectionTitle: "Today's Appointments",
    secondarySectionTitle: 'Needs Attention',
    summary: [
      { label: 'Confirmed', count: 8, color: 'blue' },
      { label: 'Checked In', count: 3, color: 'green' },
      { label: 'Awaiting Approval', count: 2, color: 'amber' },
      { label: 'Delayed', count: 1, color: 'red' },
    ],
    nba: {
      label: 'Send Approval Request',
      description: '2 customers waiting on authorization — Est. $1,240',
      count: 2,
      urgency: 'high',
    },
    queue: [
      {
        id: 'a1', refNumber: 'APT-4821', customerName: 'Patricia Moore', customerInitials: 'PM',
        vehicle: '2023 Chevrolet Silverado', status: 'waiting-approval', priority: 'urgent',
        timeLabel: 'Waiting 42 min', subLabel: 'Engine Diagnostic + Repair Auth.',
        estimatedValue: '$1,890', unreadMessages: 2, hasFlag: true,
      },
      {
        id: 'a2', refNumber: 'APT-4817', customerName: 'Robert Kim', customerInitials: 'RK',
        vehicle: '2021 Nissan Rogue', status: 'checked-in', priority: 'high',
        timeLabel: 'In since 8:30 AM', subLabel: 'CVT Service + Cabin Air Filter',
        estimatedValue: '$420',
      },
      {
        id: 'a3', refNumber: 'APT-4830', customerName: 'Angela Foster', customerInitials: 'AF',
        vehicle: '2020 Hyundai Tucson', status: 'confirmed', priority: 'medium',
        timeLabel: '11:00 AM', subLabel: 'Tire Rotation + Alignment Check',
        estimatedValue: '$180',
      },
      {
        id: 'a4', refNumber: 'APT-4825', customerName: 'Daniel Cruz', customerInitials: 'DC',
        vehicle: '2019 Kia Sorento', status: 'delayed', priority: 'high',
        timeLabel: '45 min delay', subLabel: 'Brake Pads + Rotor Replacement',
        estimatedValue: '$890', hasFlag: true,
      },
      {
        id: 'a5', refNumber: 'APT-4835', customerName: 'Lisa Zhang', customerInitials: 'LZ',
        vehicle: '2022 Mazda CX-5', status: 'confirmed', priority: 'low',
        timeLabel: '2:00 PM', subLabel: 'Oil Change + Multi-Point Inspection',
        estimatedValue: '$95',
      },
      {
        id: 'a6', refNumber: 'APT-4840', customerName: 'Michael Grant', customerInitials: 'MG',
        vehicle: '2018 Ford Escape', status: 'completed', priority: 'low',
        timeLabel: 'Done 10:15 AM', subLabel: 'A/C Recharge + Leak Test',
        estimatedValue: '$340',
      },
    ],
    navItems: [
      { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', path: '/', section: 'Main' },
      { id: 'appointments', label: 'Appointments', icon: 'CalendarClock', path: '/appointments', badge: 8, section: 'Main' },
      { id: 'service-workbench', label: 'Service Workbench', icon: 'ListChecks', path: '/workbench', section: 'Main' },
      { id: 'ros', label: 'Repair Orders', icon: 'FileText', path: '/ros', section: 'Main' },
      { id: 'customers', label: 'Customers', icon: 'Users', path: '/customers', section: 'Records' },
      { id: 'vehicles', label: 'Vehicles', icon: 'Car', path: '/vehicles', section: 'Records' },
      { id: 'settings', label: 'Settings', icon: 'Settings', path: '/settings', section: 'Account' },
    ],
  },

  dispatcher: {
    id: 'dispatcher',
    label: 'Dispatcher',
    avatarColor: 'bg-violet-600',
    primarySectionTitle: 'Dispatch Board',
    secondarySectionTitle: 'Status Overview',
    summary: [
      { label: 'Unassigned', count: 4, color: 'red' },
      { label: 'In Progress', count: 6, color: 'blue' },
      { label: 'Waiting Parts', count: 3, color: 'amber' },
      { label: 'Complete', count: 7, color: 'green' },
    ],
    nba: {
      label: 'Assign 4 Unassigned Jobs',
      description: 'Bays 2, 5, 7, 9 are available now',
      count: 4,
      urgency: 'high',
    },
    queue: [
      {
        id: 'd1', refNumber: 'RO-10295', customerName: 'Thomas Bailey', customerInitials: 'TB',
        vehicle: '2021 Ram 1500', status: 'unassigned', priority: 'urgent',
        timeLabel: 'Waiting 1h 10m', subLabel: 'Transmission Replacement',
        bay: 'Unassigned', hasFlag: true,
      },
      {
        id: 'd2', refNumber: 'RO-10288', customerName: 'Elena Vasquez', customerInitials: 'EV',
        vehicle: '2020 Audi Q5', status: 'in-progress', priority: 'high',
        timeLabel: '3h 30m elapsed', subLabel: 'Suspension Overhaul',
        bay: 'Bay 3', techAssigned: 'Jake M.',
      },
      {
        id: 'd3', refNumber: 'RO-10279', customerName: 'Chris Nolan', customerInitials: 'CN',
        vehicle: '2022 Tesla Model 3', status: 'waiting-parts', priority: 'high',
        timeLabel: 'Parts ETA: 3:00 PM', subLabel: 'High Voltage Battery Module',
        bay: 'EV Bay 1', techAssigned: 'Sarah T.',
      },
      {
        id: 'd4', refNumber: 'RO-10302', customerName: 'Amara Johnson', customerInitials: 'AJ',
        vehicle: '2019 Mercedes GLC', status: 'blocked', priority: 'urgent',
        timeLabel: 'Blocked 2h 05m', subLabel: 'Special tool required — Pending',
        bay: 'Bay 8', techAssigned: 'Mike R.', hasFlag: true,
      },
      {
        id: 'd5', refNumber: 'RO-10299', customerName: 'Frank Ortiz', customerInitials: 'FO',
        vehicle: '2017 Jeep Wrangler', status: 'unassigned', priority: 'medium',
        timeLabel: 'Waiting 25m', subLabel: 'Lift Kit Installation',
        bay: 'Unassigned',
      },
      {
        id: 'd6', refNumber: 'RO-10270', customerName: 'Hannah Lee', customerInitials: 'HL',
        vehicle: '2023 Toyota RAV4 Prime', status: 'in-progress', priority: 'medium',
        timeLabel: '1h 45m elapsed', subLabel: 'Scheduled Maintenance 30K',
        bay: 'Bay 5', techAssigned: 'Carlos D.',
      },
    ],
    navItems: [
      { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', path: '/', section: 'Main' },
      { id: 'appointments', label: 'Appointments', icon: 'CalendarClock', path: '/appointments', badge: 16, section: 'Main' },
      { id: 'dispatch', label: 'Dispatch Board', icon: 'Trello', path: '/dispatch', section: 'Main' },
      { id: 'service-workbench', label: 'Service Workbench', icon: 'ListChecks', path: '/workbench', badge: 4, section: 'Main' },
      { id: 'technicians', label: 'Technicians', icon: 'UserCheck', path: '/technicians', section: 'Team' },
      { id: 'parts', label: 'Parts', icon: 'Package', path: '/parts', section: 'Resources' },
      { id: 'settings', label: 'Settings', icon: 'Settings', path: '/settings', section: 'Account' },
    ],
  },

  sales: {
    id: 'sales',
    label: 'Sales Consultant',
    avatarColor: 'bg-orange-500',
    primarySectionTitle: "Today's Consultations",
    secondarySectionTitle: 'Pipeline',
    summary: [
      { label: 'Scheduled', count: 5, color: 'blue' },
      { label: 'Test Drives', count: 2, color: 'green' },
      { label: 'Follow-up', count: 7, color: 'amber' },
      { label: 'Hot Leads', count: 3, color: 'red' },
    ],
    nba: {
      label: 'Follow Up — 3 Hot Leads',
      description: 'Response rate drops 80% after 4 hours',
      count: 3,
      urgency: 'high',
    },
    queue: [
      {
        id: 's1', refNumber: 'LEAD-8821', customerName: 'Brandon Hicks', customerInitials: 'BH',
        vehicle: '2024 Ford Mustang Mach-E', status: 'test-drive', priority: 'urgent',
        timeLabel: 'Test drive now', subLabel: 'Trade-in: 2019 Civic | Pre-approved',
        estimatedValue: '$52,400', source: 'Web Inquiry', hasFlag: true,
      },
      {
        id: 's2', refNumber: 'LEAD-8814', customerName: 'Olivia Pham', customerInitials: 'OP',
        vehicle: '2023 Toyota Camry XSE', status: 'negotiation', priority: 'high',
        timeLabel: 'Last contact: 45m ago', subLabel: 'Financing — 72mo @ 6.9% APR',
        estimatedValue: '$31,200', source: 'Referral',
      },
      {
        id: 's3', refNumber: 'LEAD-8798', customerName: 'James Carter', customerInitials: 'JC',
        vehicle: '2024 Chevrolet Equinox EV', status: 'scheduled', priority: 'medium',
        timeLabel: '1:00 PM today', subLabel: 'First visit — EV Consultation',
        estimatedValue: '$38,900', source: 'AutoTrader',
      },
      {
        id: 's4', refNumber: 'LEAD-8810', customerName: 'Mia Rodriguez', customerInitials: 'MR',
        vehicle: '2024 BMW X3 xDrive', status: 'new', priority: 'high',
        timeLabel: 'New — 2h ago', subLabel: 'Lease inquiry submitted online',
        estimatedValue: '$58,700', source: 'Website', unreadMessages: 1, hasFlag: true,
      },
      {
        id: 's5', refNumber: 'LEAD-8801', customerName: 'Nathan Brooks', customerInitials: 'NB',
        vehicle: '2023 Honda CR-V Hybrid', status: 'scheduled', priority: 'medium',
        timeLabel: '3:30 PM today', subLabel: 'Returning customer — Lease end',
        estimatedValue: '$34,500', source: 'CRM Follow-up',
      },
      {
        id: 's6', refNumber: 'LEAD-8789', customerName: 'Sophie Anderson', customerInitials: 'SA',
        vehicle: '2022 Jeep Grand Cherokee', status: 'closed-won', priority: 'low',
        timeLabel: 'Closed 9:30 AM', subLabel: 'Deal #D-4821 — Cash purchase',
        estimatedValue: '$47,200', source: 'Showroom Walk-in',
      },
    ],
    navItems: [
      { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', path: '/', section: 'Main' },
      { id: 'appointments', label: 'Appointments', icon: 'CalendarClock', path: '/appointments', badge: 5, section: 'Main' },
      { id: 'leads', label: 'My Leads', icon: 'Target', path: '/leads', badge: 3, section: 'Main' },
      { id: 'vehicles-inv', label: 'Inventory', icon: 'Car', path: '/inventory', section: 'Sales' },
      { id: 'test-drives', label: 'Test Drives', icon: 'Route', path: '/test-drives', section: 'Sales' },
      { id: 'deals', label: 'Deals', icon: 'Handshake', path: '/deals', section: 'Sales' },
      { id: 'customers', label: 'Customers', icon: 'Users', path: '/customers', section: 'Records' },
      { id: 'settings', label: 'Settings', icon: 'Settings', path: '/settings', section: 'Account' },
    ],
  },

  manager: {
    id: 'manager',
    label: 'Manager',
    avatarColor: 'bg-slate-700',
    primarySectionTitle: 'Operations Overview',
    secondarySectionTitle: 'Blockers & Alerts',
    summary: [
      { label: 'Active ROs', count: 18, color: 'blue' },
      { label: 'Revenue Today', count: 24800, color: 'green' },
      { label: 'Blockers', count: 3, color: 'red' },
      { label: 'Deals Pending', count: 7, color: 'amber' },
    ],
    nba: {
      label: 'Review Blocked Jobs',
      description: '3 jobs stalled — estimated $4,200 revenue at risk',
      count: 3,
      urgency: 'high',
    },
    queue: [
      {
        id: 'm1', refNumber: 'ALERT-001', customerName: 'Service Department', customerInitials: 'SD',
        vehicle: 'Bay 8 — Mercedes GLC', status: 'blocked', priority: 'urgent',
        timeLabel: 'Blocked 2h 05m', subLabel: 'Special tool missing — OEM supplier',
        estimatedValue: '$2,100 at risk', hasFlag: true,
      },
      {
        id: 'm2', refNumber: 'ALERT-002', customerName: 'Parts Department', customerInitials: 'PD',
        vehicle: 'Tesla Model 3 — EV Bay', status: 'waiting-parts', priority: 'high',
        timeLabel: 'Delayed 3h+', subLabel: 'Battery module backordered — Alt. sourcing needed',
        estimatedValue: '$1,850 at risk', hasFlag: true,
      },
      {
        id: 'm3', refNumber: 'APT-4821', customerName: 'Patricia Moore', customerInitials: 'PM',
        vehicle: '2023 Chevrolet Silverado', status: 'waiting-approval', priority: 'high',
        timeLabel: 'Waiting 42 min', subLabel: 'Customer approval needed — Auth. $1,890',
        estimatedValue: '$1,890',
      },
      {
        id: 'm4', refNumber: 'LEAD-8814', customerName: 'Olivia Pham', customerInitials: 'OP',
        vehicle: '2023 Toyota Camry XSE', status: 'negotiation', priority: 'medium',
        timeLabel: 'In negotiation 45m', subLabel: 'Deal $31,200 — F&I review pending',
        estimatedValue: '$31,200',
      },
      {
        id: 'm5', refNumber: 'OPS-011', customerName: 'Unassigned Queue', customerInitials: 'UQ',
        vehicle: '4 ROs Unassigned', status: 'unassigned', priority: 'medium',
        timeLabel: '4 jobs waiting', subLabel: 'Techs Mike, Sarah available in Bay 2 & 9',
        hasFlag: true,
      },
    ],
    navItems: [
      { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', path: '/', section: 'Main' },
      { id: 'appointments', label: 'Appointments', icon: 'CalendarClock', path: '/appointments', badge: 16, section: 'Main' },
      { id: 'operations', label: 'Operations', icon: 'Activity', path: '/operations', section: 'Main' },
      { id: 'reports', label: 'Reports', icon: 'BarChart3', path: '/reports', section: 'Main' },
      { id: 'service', label: 'Service', icon: 'Wrench', path: '/service', badge: 3, section: 'Departments' },
      { id: 'sales', label: 'Sales', icon: 'TrendingUp', path: '/sales', section: 'Departments' },
      { id: 'team', label: 'Team', icon: 'Users', path: '/team', section: 'Departments' },
      { id: 'parts', label: 'Parts & Inventory', icon: 'Package', path: '/parts', section: 'Resources' },
      { id: 'settings', label: 'Settings', icon: 'Settings', path: '/settings', section: 'Account' },
    ],
  },
};

export const COMMAND_ITEMS = [
  { id: 'c1',  type: 'ro',          label: 'RO-10284 — Marcus Rivera',       sub: '2022 Honda Accord · In Progress · Bay 4' },
  { id: 'c2',  type: 'ro',          label: 'RO-10291 — Sarah Chen',          sub: '2019 Toyota Camry · Waiting Parts · Bay 2' },
  { id: 'c3',  type: 'ro',          label: 'RO-10302 — Amara Johnson',       sub: '2019 Mercedes GLC · BLOCKED · Bay 8' },
  { id: 'c4',  type: 'ro',          label: 'RO-10325 — Tony Garcia',         sub: '2021 Ram 1500 · Awaiting Approval · Bay 5' },
  { id: 'c5',  type: 'ro',          label: 'RO-10279 — Chris Nolan',         sub: '2022 Tesla Model 3 · Waiting Parts · EV Bay 1' },
  { id: 'c6',  type: 'customer',    label: 'Patricia Moore',                 sub: 'Customer · 3 vehicles on file' },
  { id: 'c7',  type: 'customer',    label: 'Brandon Hicks',                  sub: 'Customer · Hot Lead' },
  { id: 'c8',  type: 'appointment', label: 'APT-4821 — 8:00 AM',            sub: 'Patricia Moore · Silverado' },
  { id: 'c9',  type: 'deal',        label: 'Deal #D-4821 — Sophie Anderson', sub: 'Closed Won · $47,200' },
  { id: 'c10', type: 'action',      label: 'Create New Repair Order',        sub: 'Action · Service Workbench' },
  { id: 'c11', type: 'action',      label: 'Open Service Workbench',         sub: 'Action · Service Workbench' },
  { id: 'c12', type: 'action',      label: 'Open Appointment Queue',         sub: 'Action · Advisor · Dispatcher' },
  { id: 'c13', type: 'action',      label: 'Open Dispatch Board',            sub: 'Action · Dispatcher · Kanban · Bay Assignment' },
  { id: 'c14', type: 'action',      label: 'Schedule Appointment',           sub: 'Action · Advisor' },
  { id: 'c15', type: 'action',      label: 'Add New Customer',               sub: 'Action · Records' },
  { id: 'c16', type: 'action',      label: 'Generate Daily Report',          sub: 'Action · Manager' },
];